#ifndef __CONFIG__
#define __CONFIG__

#define PROGRAM_VERSION	"Version 0.5.130"

#define SPACE_BOUNCING_EFFECT	7
#define EFFECT_BOUNCING_FACTOR	20
#define MAX_SPEED_BALL_X_Y		300
#define MAX_BAT_SPEED 			20

#define BAT_WITDH				240
#define BAT_HEIGHT				160

#define UART_INTERRUPT_ENABLE 	1
#define UART_WRITE_MODE_ENABLE 	1
#define UART_BUFFER_LENGTH		20
#define UART_TRANSMIT_ENABLE 0

#define SPI_INTERRUPT_ENABLE 	1
#define SPI_SLAVE_MODE_ENABLE 	1
#define SPI_READ_MODE_ENABLE 	0

#define COLOR_PLAYER1 0x500
#define COLOR_PLAYER2 0x005

#endif
